/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/BCAddInstance': RouteRecordInfo<'/BCAddInstance', '/BCAddInstance', Record<never, never>, Record<never, never>>,
    '/BCAddNewUser': RouteRecordInfo<'/BCAddNewUser', '/BCAddNewUser', Record<never, never>, Record<never, never>>,
    '/BCBuildApiUrl': RouteRecordInfo<'/BCBuildApiUrl', '/BCBuildApiUrl', Record<never, never>, Record<never, never>>,
    '/BCChangeAuthType': RouteRecordInfo<'/BCChangeAuthType', '/BCChangeAuthType', Record<never, never>, Record<never, never>>,
    '/BCDatabaseBackup': RouteRecordInfo<'/BCDatabaseBackup', '/BCDatabaseBackup', Record<never, never>, Record<never, never>>,
    '/BCEnableDevMode': RouteRecordInfo<'/BCEnableDevMode', '/BCEnableDevMode', Record<never, never>, Record<never, never>>,
    '/BCEnableIntegration': RouteRecordInfo<'/BCEnableIntegration', '/BCEnableIntegration', Record<never, never>, Record<never, never>>,
    '/BCImportLicense': RouteRecordInfo<'/BCImportLicense', '/BCImportLicense', Record<never, never>, Record<never, never>>,
  }
}
